name: cotmade
description: Easy Stay, Anywhere, Anywhere.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  get:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_sign_in: ^6.2.2
  image_picker:
  flutter_svg:
  timeago:
  custom_rating_bar:
  flutter_faq:
  video_compress:
  flutter_screenutil:
  photo_manager:
  uuid:
  video_player: ^2.9.2
  flutter_staggered_grid_view:
  date_format:
  cached_network_image:
  file_selector:
  flutter_spinkit:
  email_otp:
  is_first_run:
  flick_video_player: ^0.9.0
  flutter_rating_bar:
  flutterwave_standard: ^1.0.8
  intl:
  flutter_onboarding_slider:
  shared_preferences:
  intro_slider:
  http:
  firebase_messaging:
  printing:
  fl_chart: ^0.63.0
  carousel_slider:
  file_picker:
  permission_handler:
  flutter_animate:
  share_plus: ^11.1.0
  upgrader:
  flutter_sound:
  flutter_cache_manager:
  audioplayers:
  just_audio:
  flutter_local_notifications: ^19.3.1
  webview_flutter:
  url_launcher:
  image:
  speech_to_text:
  tflite_flutter:
  flutter_map:
  latlong2:
  geocoding:
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
#  icons_launcher: ^3.0.3

#icons_launcher:
 # image_path: "images/icon.png"
  #platforms:
   # android:
    #  enable: true
    #ios:
     # enable: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - audio/
    - tflite/housing_model.tflite
    - tflite/label.txt
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
