name: cotmade
description: Easy Stay, Anytime, Anywhere in Africa.

version: 1.0.9+5

environment:
  sdk: ">=3.0.0 <3.5.4"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.1
  google_sign_in:
  image_picker:
  flutter_svg:
  timeago:
  custom_rating_bar:
  flutter_faq:
  video_compress: ^3.1.3
  flutter_screenutil:
  photo_manager: ^3.6.4
  uuid:
  video_player: ^2.9.2
  flutter_staggered_grid_view: ^0.7.0
  date_format: ^2.0.9
  cached_network_image: ^3.4.1
  video_uploader: ^1.3.0
  file_selector: ^1.0.3
  flutter_spinkit: ^5.2.1
  email_otp: ^3.0.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  is_first_run: ^1.0.0
  flutter_onboarding:
  flutter_animate: ^4.5.2
  introduction_screen: ^3.1.14
  google_fonts: ^6.2.1
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.2
  visibility_detector: ^0.4.0+2
  mailer: ^6.4.1
  carousel_slider: ^5.0.0
  file_picker: ^8.3.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.11
  provider: ^6.1.2
  share: ^2.0.0
  flutter_typeahead: ^5.2.0 
  flutter_email_sender: ^6.0.3
  flutter_cache_manager: ^3.4.1
  url_launcher: ^6.3.1
  flick_video_player: ^0.9.0
  flutter_html:
  flutter_rating_bar: ^4.0.1
  flutterwave_standard: ^1.0.8
  intl: ^0.20.2
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.0.15
  intro_slider: ^4.2.1
  http: ^1.3.0
  firebase_messaging: ^15.1.5
  printing: ^5.6.0
  fl_chart: ^0.69.2
  in_app_purchase: ^3.0.0
  upgrader:
  dio: ^5.7.0
  flutter_cached_video_player_plus:
  flutter_sound:
  just_audio: ^0.9.43
  flutter_local_notifications: ^17.0.0
  webview_flutter: ^4.7.0
  image: ^4.3.0
  speech_to_text: ^6.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  icons_launcher: ^3.0.1

icons_launcher:
  image_path: "images/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/audio/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
