platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

def flutter_install_all_ios_pods(flutter_application_path)
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')), binding)
end
