platform :ios, '13.0'

target 'Runner' do
  use_frameworks!

  pod 'CoreAudioTypes', :path => '/System/Library/Frameworks/CoreAudioTypes.framework'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
