name: Flutter Android Build

on:
  push:
    branches:
      - android-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable
      
      - name: Delete build folders
        run: rm -rf build android/app/build android/build      

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Set permissions on gradlew
        run: chmod +x android/gradlew

      - name: Build APK and AAB
        working-directory: android
        run: |
          ./gradlew clean assembleRelease bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK and AAB
        if: ${{ false }} 
        uses: actions/upload-artifact@v4
        with:
          name: flutter-android-artifacts
          path: |
            android/app/build/outputs/bundle/release/*.apk
            android/app/build/outputs/bundle/release/*.aab

      - name: 📤 Upload APK and AAB via uppy.sh
        run: |
          for file in \
            android/build/app/outputs/flutter-apk/app-release.apk \
            android/build/app/outputs/bundle/release/app-release.aab; do

            if [ -f "$file" ]; then
              echo "📤 Uploading $file ..."
              url=$(curl --upload-file "$file" "https://uppy.sh/$(basename "$file")")
              echo "✅ Uploaded: $url"
            else
              echo "❌ Not found: $file"
            fi
          done

